### ISSUE TITLE
Depreciated

### ISSUE THREAD

**Issue by GErpeldinger** [umanit/phinx-bundle#2]
Hello,

The parameter `kernel.root_dir` used in `DependencyInjection\Configuration` is depreciated since Symfony 4.2
Source : https://symfony.com/blog/new-in-symfony-4-2-important-deprecations

In `README.md`, in the point 5 you said `add bundle config to config/packages/umanit_phinx.yml`, Symfony don't get the config file if the extension is `.yml` need to use `.yaml` instead, don't know if it's new, i'm on a Symfony 5.3

Thanks for your work.

**Comment by DjLeChuck** [comment]
Hi @GErpeldinger ,

Thank you for your issue!

The new version [2.0.1](https://github.com/umanit/phinx-bundle/releases/tag/2.0.1) address your remarks. 👍🏻
